### ISSUE TITLE
button does not work

### ISSUE THREAD

**Issue by harrywang** [alex1007/mailman-on-aws#17]
manage subscription button in the following page does not work
![screenshot 2016-12-04 14 39 13](https://cloud.githubusercontent.com/assets/595772/20864511/85fd5d20-ba2f-11e6-88c3-04a8db8bed31.png)

**Comment by alex1007** [comment]
It is useless. redirecting to current page

**Comment by harrywang** [comment]
it should direct to which page? How to fix this?

**Comment by alex1007** [comment]
it is fixed. the button can work

**Comment by harrywang** [comment]
How? Add document link!

**Comment by alex1007** [comment]
What link? Solution is in the comment
